### ISSUE TITLE
Auto-generated code tool

### ISSUE THREAD

**Issue by bradvido** [citrix/ShareFile-Java#14]
Much of the code in this project says:
```
<auto-generated>
//     This code was generated by a tool.
...
```

Where is the tool that was used to generate the code? It would be useful for forking this and updating it to include more recent things, like workflows: https://github.com/citrix/ShareFile-Java/issues/13

**Comment by rgmills** [comment]
@bradvido The tool itself is an in-house tool that performs some reflection over internal assemblies.  We don't currently publish anything such as swagger/openapi specs due to some quirky things we do that are tough to resolve without a decent amount of customization of the output client.  So, we won't be able to provide that unfortunately.

However, we're working on coming up with a better process that will hopefully see updated APIs made available at the same time they are released (we're currently releasing ShareFile API updates roughly ever week).

**Comment by bradvido** [comment]
😞
